### ISSUE TITLE
 Uncaught Pecee\SimpleRouter\Exceptions\HttpException: Route "/login/" or method "get" not allowed.

### ISSUE THREAD

**Issue by mertbuldur** [skipperbent/simple-php-router#385]
Hi ,   My route file is 
`Router::get('/login','Application\Controllers\login@index')->name('login');
Router::post('/login','Application\Controllers\login@store')->name('login.post');`

But I have error . My error is 
`Fatal error: Uncaught Pecee\SimpleRouter\Exceptions\HttpException: Route "/login/" or method "get" not allowed. in /Applications/XAMPP/xamppfiles/htdocs/udemy2/vendor/pecee/simple-router/src/Pecee/SimpleRouter/Router.php:287 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/udemy2/vendor/pecee/simple-router/src/Pecee/SimpleRouter/SimpleRouter.php(52): Pecee\SimpleRouter\Router->routeRequest() #1 /Applications/XAMPP/xamppfiles/htdocs/udemy2/app/Router.php(12): Pecee\SimpleRouter\SimpleRouter::start() #2 /Applications/XAMPP/xamppfiles/htdocs/udemy2/index.php(4): Application\Router::start() #3 {main} thrown in /Applications/XAMPP/xamppfiles/htdocs/udemy2/vendor/pecee/simple-router/src/Pecee/SimpleRouter/Router.php on line 287`

What is Problem ? 
Thank Yo.

**Comment by skipperbent** [comment]
Hi @mertbuldur.

- Which version of the library are you using?
- Which version of PHP are you using?

**This could be one of the reasons why you are receiving that error:**
- Most common: Routes are not loaded properly - therefore no routes match the current url. 
Solution: You can verify that routes are loaded by calling `SimpleRouter::router()->getRoutes()`.

- `REQUEST_URI` from your webserver is incorrect, making the urls fail to match.
Solution: Verify that `SimpleRouter::request()->getUrl()` returns the same url as in your web-browser.

**Please run this after your routes has been added and paste the contents in this issue:**

```php
// LOAD YOUR ROUTES HERE...

try {
        static::start();
    } catch(\Exception $e) {
}

$debugInfo =[
    'unencoded_url' => SimpleRouter::request()->getHeader('unencoded-url'),
    'request-uri'   => SimpleRouter::request()->getHeader('request-uri'),
    'url'           => SimpleRouter::request()->getUrl(),
    'method'        => SimpleRouter::request()->getMethod(),
    'host'          => SimpleRouter::request()->getHost(),
    'loaded_routes' => SimpleRouter::request()->getLoadedRoutes(),
    'all_routes'    => SimpleRouter::router()->getRoutes(),
    'boot_managers' => SimpleRouter::router()->getBootManagers(),
    'csrf_verifier' => SimpleRouter::router()->getCsrfVerifier(),
];

echo '<pre>';
echo var_dump($debugInfo);
echo '</pre>';
exit;
```

You can find a working demo using this project here:
https://github.com/skipperbent/simple-router-demo

/ Simon

**Comment by mertbuldur** [comment]
thank you , @skipperbent  I use now 
`// LOAD YOUR ROUTES HERE...

try {
        static::start();
    } catch(\Exception $e) {
}
`
problem is end :)

**Comment by skipperbent** [comment]
@mertbuldur 

I updated the example, it should be `SimpleRouter::start()` instead of `static::start()`.

You shouldn't catch the exception like that - then you won't know whenever a 404 etc. are received and it WILL eventually cause problems as errors are already handled internally by the library.

Try to add this route instead of the ones in your first post and see if that will work:

```php
// Will match GET and POST
Router::form('/login', function() {
    return 'OK';
})->name('login');
```

**If the above doesn't work, please please provide the following info:**

- The contents of the callback method.
- What version of the library you are using.
- The contents generated by the debug code in my previous post.

/ Simon

**Comment by mertbuldur** [comment]
My library version is  "pecee/simple-router": "^3.7"
Php Version is 7.1

**Comment by skipperbent** [comment]
@mertbuldur 

Thanks.

**Can you please please provide the following info:**

- The contents of the callback method.
- The contents generated by the debug code in my previous post.

/ Simon

**Comment by skipperbent** [comment]
Closing this issue due to inactivity. Feel free to reopen or create a new ticket if you still experience issues.

/ Simon
